apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  namespace: java-spring
  labels:
    app.kubernetes.io/name: java-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-spring
    spec:
      containers:
        - name: app
          image: httpd:2.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
