apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  namespace: java-spring
  labels:
    app.kubernetes.io/name: java-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-spring
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-spring@sha256:4b78ec5b32e79d95b8a9e625a441d2be06d6568811c5766a6a243fefb3980d5d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
