apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-spring
  namespace: java-spring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: java-spring.sesac.already11.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-spring
                port:
                  number: 80
  tls:
    - hosts:
        - java-spring.sesac.already11.cloud
      secretName: java-spring-tls
