apiVersion: v1
kind: Service
metadata:
  name: java-spring
  namespace: java-spring
  labels:
    app.kubernetes.io/name: java-spring
spec:
  selector:
    app.kubernetes.io/name: java-spring
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
