apiVersion: apps/v1
kind: Deployment
metadata:
  name: power
  namespace: power
  labels:
    app.kubernetes.io/name: power
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: power
  template:
    metadata:
      labels:
        app.kubernetes.io/name: power
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/power@sha256:cbf67d4a62c40b85e756c3b2155ad5e27fd943cbc67b204d5ff9b9d42c4e64d5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
