apiVersion: v1
kind: Service
metadata:
  name: power
  namespace: power
  labels:
    app.kubernetes.io/name: power
spec:
  selector:
    app.kubernetes.io/name: power
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
