apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-new
  namespace: java-new
  labels:
    app.kubernetes.io/name: java-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-new
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-new
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-new@sha256:4933f1ec6fbc679b17f491b6e90ae354c80553010dd0279fd98a2ac798101257
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
