apiVersion: v1
kind: Service
metadata:
  name: java-send
  namespace: java-send
  labels:
    app.kubernetes.io/name: java-send
spec:
  selector:
    app.kubernetes.io/name: java-send
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
