apiVersion: v1
kind: Service
metadata:
  name: node-test-server
  namespace: node-test-server
  labels:
    app.kubernetes.io/name: node-test-server
spec:
  selector:
    app.kubernetes.io/name: node-test-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
