apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  namespace: node-server
  labels:
    app.kubernetes.io/name: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-server
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/node-server:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
