apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-gradle-hub
  namespace: java-gradle-hub
  labels:
    app.kubernetes.io/name: java-gradle-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-gradle-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-gradle-hub
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-gradle-hub@sha256:42768b46bdf703eabf2d90a016d3273f3ce6bb9a1290e5716b3c8a6df6e76ca2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
