apiVersion: v1
kind: Service
metadata:
  name: java-gradle-hub
  namespace: java-gradle-hub
  labels:
    app.kubernetes.io/name: java-gradle-hub
spec:
  selector:
    app.kubernetes.io/name: java-gradle-hub
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
