apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sejin-123
  namespace: java-sejin-123
  labels:
    app.kubernetes.io/name: java-sejin-123
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-sejin-123
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-sejin-123
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-sejin-123@sha256:1aab808e2c9c8384fac5f687439efcac74ee21cb4eee30b0806a2b69d2a87b2c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
