apiVersion: v1
kind: Service
metadata:
  name: java-sejin-123
  namespace: java-sejin-123
  labels:
    app.kubernetes.io/name: java-sejin-123
spec:
  selector:
    app.kubernetes.io/name: java-sejin-123
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
