apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sec-test
  namespace: java-sec-test
  labels:
    app.kubernetes.io/name: java-sec-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-sec-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-sec-test
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-sec-test:05081cd7f82c121ca58e0d31b6701536bac08a55
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
