apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcdawegegrh
  namespace: abcdawegegrh
  labels:
    app.kubernetes.io/name: abcdawegegrh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abcdawegegrh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abcdawegegrh
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/abcdawegegrh@sha256:57115329535ff65538042d59c74e03486fa1a512936e3c11294f455e405fa2c1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
