apiVersion: v1
kind: Service
metadata:
  name: abcdawegegrh
  namespace: abcdawegegrh
  labels:
    app.kubernetes.io/name: abcdawegegrh
spec:
  selector:
    app.kubernetes.io/name: abcdawegegrh
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
