apiVersion: v1
kind: Service
metadata:
  name: ergerh
  namespace: ergerh
  labels:
    app.kubernetes.io/name: ergerh
spec:
  selector:
    app.kubernetes.io/name: ergerh
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
