apiVersion: apps/v1
kind: Deployment
metadata:
  name: already-java
  namespace: already-java
  labels:
    app.kubernetes.io/name: already-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: already-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: already-java
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/already-java@sha256:d91440a0ff2ed987d2f0e8252cdbe7c9604c90256ec1daa9520e7c96846890df
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
