apiVersion: v1
kind: Service
metadata:
  name: already-java
  namespace: already-java
  labels:
    app.kubernetes.io/name: already-java
spec:
  selector:
    app.kubernetes.io/name: already-java
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
