apiVersion: v1
kind: Service
metadata:
  name: java-test-server
  namespace: java-test-server
  labels:
    app.kubernetes.io/name: java-test-server
spec:
  selector:
    app.kubernetes.io/name: java-test-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
