apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-test
  namespace: node-test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: node-test.sesac.already11.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-test
                port:
                  number: 80
  tls:
    - hosts:
        - node-test.sesac.already11.cloud
      secretName: node-test-tls
