apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-project
  namespace: java-spring-project
  labels:
    app.kubernetes.io/name: java-spring-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-spring-project
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-spring-project
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-spring-project@sha256:3484403e1f24dd3e297833362fed4d67eb8b40ea372eba152b4dc83e68c787b6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
