apiVersion: v1
kind: Service
metadata:
  name: java-spring-project
  namespace: java-spring-project
  labels:
    app.kubernetes.io/name: java-spring-project
spec:
  selector:
    app.kubernetes.io/name: java-spring-project
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
