apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-kr
  namespace: backstage-kr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: backstage-kr.sesac.already11.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage-kr
                port:
                  number: 80
  tls:
    - hosts:
        - backstage-kr.sesac.already11.cloud
      secretName: backstage-kr-tls
