apiVersion: v1
kind: Service
metadata:
  name: backstage-kr
  namespace: backstage-kr
  labels:
    app.kubernetes.io/name: backstage-kr
spec:
  selector:
    app.kubernetes.io/name: backstage-kr
  ports:
    - name: http
      port: 80
      targetPort: 7007
      protocol: TCP
  type: ClusterIP
