apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-serjin
  namespace: java-serjin
  labels:
    app.kubernetes.io/name: java-serjin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-serjin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-serjin
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-serjin:0b80347d04e6fe3a3cf74ff58cfd9f9dad8b8588
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
