apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-serjin
  namespace: java-serjin
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: java-serjin.sesac.already11.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-serjin
                port:
                  number: 80
