apiVersion: v1
kind: Service
metadata:
  name: java-server2
  namespace: java-server2
  labels:
    app.kubernetes.io/name: java-server2
spec:
  selector:
    app.kubernetes.io/name: java-server2
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
