apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sec-dev
  namespace: java-sec-dev
  labels:
    app.kubernetes.io/name: java-sec-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-sec-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-sec-dev
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-sec-dev:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
