apiVersion: v1
kind: Service
metadata:
  name: java-sec-dev
  namespace: java-sec-dev
  labels:
    app.kubernetes.io/name: java-sec-dev
spec:
  selector:
    app.kubernetes.io/name: java-sec-dev
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
