apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-sec
  namespace: java-sec
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: java-sec.sesac.already11.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-sec
                port:
                  number: 80
  tls:
    - hosts:
        - java-sec.sesac.already11.cloud
      secretName: java-sec-tls
