apiVersion: v1
kind: Service
metadata:
  name: test-test
  namespace: test-test
  labels:
    app.kubernetes.io/name: test-test
spec:
  selector:
    app.kubernetes.io/name: test-test
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
