apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test
  namespace: java-test
  labels:
    app.kubernetes.io/name: java-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-test
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-test@sha256:5668c49dcad228fce58d5afd7d03c27f648f94acab3bf0f76e5465ee29a35368
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
