apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sejin
  namespace: java-sejin
  labels:
    app.kubernetes.io/name: java-sejin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-sejin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-sejin
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-sejin:a7c9ffc2ad9435c3115f6d15a610aec85de7b5b2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
