apiVersion: v1
kind: Service
metadata:
  name: java-sejin
  namespace: java-sejin
  labels:
    app.kubernetes.io/name: java-sejin
spec:
  selector:
    app.kubernetes.io/name: java-sejin
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
