apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-boot
  namespace: java-spring-boot
  labels:
    app.kubernetes.io/name: java-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-spring-boot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-spring-boot
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-spring-boot@sha256:6f952f86f8e8dc3e82720a5ddf834c9918f904badb3ce616236177fe40a2460e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
