apiVersion: v1
kind: Service
metadata:
  name: java-spring-boot
  namespace: java-spring-boot
  labels:
    app.kubernetes.io/name: java-spring-boot
spec:
  selector:
    app.kubernetes.io/name: java-spring-boot
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
