apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-seijn-333
  namespace: java-seijn-333
  labels:
    app.kubernetes.io/name: java-seijn-333
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-seijn-333
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-seijn-333
    spec:
      containers:
        - name: app
          image: 710232982381.dkr.ecr.ap-northeast-2.amazonaws.com/java-seijn-333@sha256:e226e84346924609f774dfa708c53aca49a0092b3729127b21aad51b3e36bd47
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
