apiVersion: v1
kind: Service
metadata:
  name: java-seijn-333
  namespace: java-seijn-333
  labels:
    app.kubernetes.io/name: java-seijn-333
spec:
  selector:
    app.kubernetes.io/name: java-seijn-333
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
